import "./globals.css"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

export const metadata = {
  title: "Eventier",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased bg-neutral-100`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
